# Generated by Django 4.1.13 on 2025-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_profile_pic_alter_room_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
